#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PW.Resource", IsApplication=true)]

namespace PW
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int list = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int DateOfIssue = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int Description = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int PhoneNumber = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int Thumbnail = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int Title = 2131034122;
			
			// aapt resource value: 0x7f050006
			public const int addReminderButton = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int dateText = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int fragmentContainer = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int infoText = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int phoneText = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int textView4 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddReminder = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReminderView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int AddReminderHeader = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Author = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int CallHistory = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Reminder = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Server = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int Title = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
